version: "3.5"
services:
  harmony-reference:
    container_name: harmony-reference
    image: registry.mobilejazz.com/harmony/documentation:$HARMONY_REFERENCE_VERSION
    restart: unless-stopped
    networks:
        common_network:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=common_network"
      # Defines router rules for the entrypoint we've defined as "web" (http)
      - "traefik.http.routers.harmony-reference.entrypoints=web"
      - "traefik.http.routers.harmony-reference.rule=Host(`harmony.mobilejazz.com`)"
      - "traefik.http.middlewares.harmony-reference-https-redirect.redirectscheme.scheme=https"
      # Defines router rules for the entrypoint we've defined as "websecure" (https)
      - "traefik.http.routers.harmony-reference-secure.entrypoints=websecure"
      - "traefik.http.routers.harmony-reference-secure.rule=Host(`harmony.mobilejazz.com`)"
      - "traefik.http.routers.harmony-reference-secure.tls=true"
      - "traefik.http.routers.harmony-reference-secure.tls.certresolver=defaultResolver"
networks:
    common_network:
        external: true
        name: 'common_network'

